- name: Backend Setup
  hosts: all
  become: true
  tasks:
    - name: Disable default version of Nodejs
      ansible.builtin.shell: dnf module disable nodejs -y

    - name: Enable Nodejs 18 version
      ansible.builtin.shell: dnf module enable nodejs:18 -y

    - name: Install Nodejs
      ansible.builtin.dnf:
        name: nodejs
        state: installed

    - name: Copy Mysql repo file
      ansible.builtin.copy:
        src: backend.service
        dest: /etc/systemd/system/backend.service

    - name: Adding application user
      ansible.builtin.user:
        name: expense

    - name: Remove existing content App folder
      ansible.builtin.file:
        path: /app
        state: absent

    - name: Create a App folder
      ansible.builtin.file:
        path: /app
        state: directory

    - name: Download and extract app content
      ansible.builtin.unarchive:
        src: https://expense-artifacts.s3.amazonaws.com/frontend.zip
        dest: /app
        remote_src: yes

    - name: Download dependencies
      community.general.npm:
        path: /app

    - name: Start/Enable backend service
      ansible.builtin.systemd_service:
        name: backend
        state: restarted
        enable: true

    - name: Installing mysql client
      ansible.builtin.dnf:
        name: mysql
        state: installed

    - name: Loading mysql schema
      community.mysql.mysql_db:
        state: dump
        name: all
        target: /app/schema/backend.sql
        login_user: root
        login_password: ExpenseApp@1
        login_host: mysql-dev.satishreddy.org
