- name: Install nginx
  ansible.builtin.dnf:
    name: nginx
    state: installed

- name: Copy expense configuration file
  ansible.builtin.copy:
    src: expense.conf
    dest: /etc/nginx/default.d/expense.conf

- name: Load app prerequisites
  ansible.builtin.include_role:
    name: common
    tasks_from: app_prereq

- name: Start/Enable nginx service
  ansible.builtin.systemd_service:
    name: nginx
    enabled: true
    state: restarted