format_version: 10
pipelines:
  deploy:
    group: defaultGroup
    label_template: "foo-1.0-${COUNT}"
    lock_behavior: true
    display_order: -1
    materials:
      ansible:
        git: https://github.com/satishreddysr777/expense-ansible.git
        shallow_clone: false
        auto_update: true
        branch: main
    stages:
      - DEV:
          fetch_materials: true
          approval:
            type: manual
          jobs:
            deployment:
              timeout: 0
              tasks:
                - exec:
                    command: ls -l
                    run_if: passed
