format_version: 10
pipelines:
  frontend:
    group: defaultGroup
    label_template: "${COUNT}"
    lock_behavior: none
    display_order: -1
    materials:
      ansible:
        git: https://github.com/satishreddysr777/expense-ansible.git
        shallow_clone: false
        auto_update: true
        branch: main
    stages:
      - DEV:
          fetch_materials: true
          approval:
            type: manual
            allow_only_on_success: true
          jobs:
            deployment:
              timeout: 0
              tasks:
                - exec:
                    command: ansible-playbook
                    arguments: ["-i", "frontend-dev.satishreddy.org,", "-e", "ansible_user=centos", "-e", "ansible_password=DevOps321", "expense.yml", "-e", "service_name=frontend", "-e", "env=dev"]

      - QA:
          fetch_materials: true
          approval:
            type: manual
            allow_only_on_success: true
          jobs:
            deployment:
              timeout: 0
              tasks:
                - exec:
                    command: ls
                    arguments:
                      - -l
                      - -A
                    run_if: passed


      - UAT:
          fetch_materials: true
          approval:
            type: manual
            allow_only_on_success: true
          jobs:
            deployment:
              timeout: 0
              tasks:
                - exec:
                    command: ls
                    arguments:
                      - -l
                      - -A
                    run_if: passed



      - PROD:
          fetch_materials: true
          approval:
            type: manual
            allow_only_on_success: true
          jobs:
            deployment:
              timeout: 0
              tasks:
                - exec:
                    command: ls
                    arguments:
                      - -l
                      - -A
                    run_if: passed
