- name: Remove existing content App folder
  ansible.builtin.file:
    path: "{{ app_location }}"
    state: absent

- name: Create a App folder
  ansible.builtin.file:
    path: "{{ app_location }}"
    state: directory

- name: Download and extract app content
  ansible.builtin.unarchive:
    src: https://expense-artifacts.s3.amazonaws.com/{{ component }}.zip
    dest: "{{ app_location }}"
    remote_src: yes